import { type Dirent } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = process.cwd();
const TARGET_DIRS = ['public', 'src/assets'];
const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg']);
const MAX_WIDTH = 1200;
const WEBP_QUALITY = 75;

type OptimizationEntry = {
  sourceAbsolute: string;
  webpAbsolute: string;
  sourcePublicPath: string;
  webpPublicPath: string;
  sourceBytes: number;
  webpBytes: number;
};

const formatBytes = (bytes: number) => {
  if (bytes === 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  const value = bytes / 1024 ** index;
  return `${value.toFixed(index === 0 ? 0 : 2)} ${units[index]}`;
};

const toPosixPath = (value: string) => value.split(path.sep).join('/');

const toPublicPath = (absolutePath: string) => {
  const relative = toPosixPath(path.relative(ROOT, absolutePath));
  return relative.startsWith('public/') ? `/${relative.slice('public/'.length)}` : `/${relative}`;
};

const walkFiles = async (directory: string): Promise<string[]> => {
  let entries: Dirent[] = [];
  try {
    entries = await fs.readdir(directory, { withFileTypes: true });
  } catch {
    return [];
  }

  const files = await Promise.all(
    entries.map(async (entry) => {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) return walkFiles(absolute);
      return [absolute];
    })
  );

  return files.flat();
};

const isOptimizableImage = (absolutePath: string) => {
  const ext = path.extname(absolutePath).toLowerCase();
  if (!IMAGE_EXTENSIONS.has(ext)) return false;
  if (absolutePath.toLowerCase().endsWith('.webp')) return false;
  return true;
};

const optimizeImage = async (sourceAbsolute: string): Promise<OptimizationEntry | null> => {
  const parsed = path.parse(sourceAbsolute);
  const webpAbsolute = path.join(parsed.dir, `${parsed.name}.webp`);

  try {
    await fs.access(webpAbsolute);
    console.log(`⏭️  Skipped (already optimized): ${toPosixPath(path.relative(ROOT, sourceAbsolute))}`);
    return null;
  } catch {
    // Continue when WebP file does not exist.
  }

  const sourceStat = await fs.stat(sourceAbsolute);

  /**
   * WebP keeps strong quality at lower file sizes for photos and UI images.
   * A 1200px max width + quality 75 is a practical balance for web delivery:
   * visually crisp on common screens while substantially reducing transfer bytes.
   */
  await sharp(sourceAbsolute)
    .rotate()
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .webp({ quality: WEBP_QUALITY })
    .toFile(webpAbsolute);

  const webpStat = await fs.stat(webpAbsolute);
  return {
    sourceAbsolute,
    webpAbsolute,
    sourcePublicPath: toPublicPath(sourceAbsolute),
    webpPublicPath: toPublicPath(webpAbsolute),
    sourceBytes: sourceStat.size,
    webpBytes: webpStat.size,
  };
};

const writeManifest = async (entries: OptimizationEntry[]) => {
  const manifestPath = path.join(ROOT, 'src/generated/image-manifest.ts');
  const mapping = Object.fromEntries(
    entries.map((entry) => [entry.sourcePublicPath, entry.webpPublicPath]).sort(([a], [b]) => a.localeCompare(b))
  );

  const fileContent = `// Auto-generated by scripts/optimize-images.ts\n// Do not edit manually.\n\nexport const imageOptimizationManifest: Record<string, string> = ${JSON.stringify(mapping, null, 2)};\n`;

  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, fileContent, 'utf8');
};

const run = async () => {
  const targets = TARGET_DIRS.map((directory) => path.join(ROOT, directory));
  const allFiles = (await Promise.all(targets.map((directory) => walkFiles(directory)))).flat();
  const sourceImages = allFiles.filter(isOptimizableImage);

  if (sourceImages.length === 0) {
    console.log('No images found in /public or /src/assets.');
    await writeManifest([]);
    return;
  }

  const optimizedEntries: OptimizationEntry[] = [];

  for (const sourceAbsolute of sourceImages) {
    const entry = await optimizeImage(sourceAbsolute);
    if (!entry) continue;

    optimizedEntries.push(entry);
    const savedBytes = entry.sourceBytes - entry.webpBytes;
    const savedPercent = entry.sourceBytes > 0 ? (savedBytes / entry.sourceBytes) * 100 : 0;

    console.log(
      `✅ ${toPosixPath(path.relative(ROOT, sourceAbsolute))} | ` +
        `${formatBytes(entry.sourceBytes)} -> ${formatBytes(entry.webpBytes)} ` +
        `(${savedPercent.toFixed(1)}% saved)`
    );
  }

  const existingWebpFiles = allFiles.filter((file) => path.extname(file).toLowerCase() === '.webp');
  const refreshedEntries: OptimizationEntry[] = [];

  for (const sourceAbsolute of sourceImages) {
    const parsed = path.parse(sourceAbsolute);
    const webpAbsolute = path.join(parsed.dir, `${parsed.name}.webp`);
    if (!existingWebpFiles.includes(webpAbsolute) && !optimizedEntries.find((entry) => entry.webpAbsolute === webpAbsolute)) {
      continue;
    }

    const sourceStat = await fs.stat(sourceAbsolute);
    const webpStat = await fs.stat(webpAbsolute);

    refreshedEntries.push({
      sourceAbsolute,
      webpAbsolute,
      sourcePublicPath: toPublicPath(sourceAbsolute),
      webpPublicPath: toPublicPath(webpAbsolute),
      sourceBytes: sourceStat.size,
      webpBytes: webpStat.size,
    });
  }

  await writeManifest(refreshedEntries);

  const totalSourceBytes = refreshedEntries.reduce((sum, entry) => sum + entry.sourceBytes, 0);
  const totalWebpBytes = refreshedEntries.reduce((sum, entry) => sum + entry.webpBytes, 0);
  const totalSaved = totalSourceBytes - totalWebpBytes;
  const totalSavedPercent = totalSourceBytes > 0 ? (totalSaved / totalSourceBytes) * 100 : 0;

  console.log('\nImage optimization summary');
  console.log(`- scanned images: ${sourceImages.length}`);
  console.log(`- newly optimized: ${optimizedEntries.length}`);
  console.log(`- total optimized images: ${refreshedEntries.length}`);
  console.log(`- original total: ${formatBytes(totalSourceBytes)}`);
  console.log(`- optimized total: ${formatBytes(totalWebpBytes)}`);
  console.log(`- total savings: ${formatBytes(totalSaved)} (${totalSavedPercent.toFixed(1)}%)`);
};

run().catch((error) => {
  console.error('Image optimization failed:', error);
  process.exit(1);
});
